name: mts
description: "Foreground & background location tracking app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2
  

dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.8
  connectivity_plus: ^5.0.1

  # Firebase (optional)
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_database: ^12.0.1

  # Maps & Location
  google_maps_flutter: ^2.4.0
  geolocator: ^14.0.2
  location: ^8.0.1
  intl: ^0.18.1
  excel: ^2.0.0
  path_provider: ^2.0.15
  share_plus: ^11.0.0

  # Permissions
  permission_handler: ^12.0.1

  # Background & Foreground execution
  flutter_foreground_task: ^7.5.2
  android_alarm_manager_plus: ^5.0.0
  workmanager: ^0.9.0+3
  flutter_background: ^1.3.0+1

  # Notifications
  flutter_local_notifications: ^19.4.2

  # Storage
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: 0.14.4
  flutter_native_splash: 2.3.3

flutter:
  uses-material-design: true
  assets:
    - lib/assets/download.png
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/download.png"


flutter_native_splash:
  color: "#2E5D5D" # background color of splash
  image: "lib/assets/download.png"
  android: true
  ios: true
  web: true  