// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnY4qYOHXAvRXGn6TvZwtY7r3JWRgswuI',
    appId: '1:881025600631:web:54eabf18fe5ce16cab8a72',
    messagingSenderId: '881025600631',
    projectId: 'srimanjunathalocationservices',
    authDomain: 'srimanjunathalocationservices.firebaseapp.com',
    databaseURL: 'https://srimanjunathalocationservices-default-rtdb.firebaseio.com',
    storageBucket: 'srimanjunathalocationservices.firebasestorage.app',
    measurementId: 'G-FWS2KX15EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABt2DuXWZ01s90R0tzP6I1QpsFcSSNDcE',
    appId: '1:881025600631:android:d72ab823fe63e910ab8a72',
    messagingSenderId: '881025600631',
    projectId: 'srimanjunathalocationservices',
    databaseURL: 'https://srimanjunathalocationservices-default-rtdb.firebaseio.com',
    storageBucket: 'srimanjunathalocationservices.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIWfXCWH6Le92rDNG6tYxhYIXPHuRNyFg',
    appId: '1:881025600631:ios:db6790c4d9e37832ab8a72',
    messagingSenderId: '881025600631',
    projectId: 'srimanjunathalocationservices',
    databaseURL: 'https://srimanjunathalocationservices-default-rtdb.firebaseio.com',
    storageBucket: 'srimanjunathalocationservices.firebasestorage.app',
    iosBundleId: 'com.example.employeeloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIWfXCWH6Le92rDNG6tYxhYIXPHuRNyFg',
    appId: '1:881025600631:ios:db6790c4d9e37832ab8a72',
    messagingSenderId: '881025600631',
    projectId: 'srimanjunathalocationservices',
    databaseURL: 'https://srimanjunathalocationservices-default-rtdb.firebaseio.com',
    storageBucket: 'srimanjunathalocationservices.firebasestorage.app',
    iosBundleId: 'com.example.employeeloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnY4qYOHXAvRXGn6TvZwtY7r3JWRgswuI',
    appId: '1:881025600631:web:858e47e919c8c747ab8a72',
    messagingSenderId: '881025600631',
    projectId: 'srimanjunathalocationservices',
    authDomain: 'srimanjunathalocationservices.firebaseapp.com',
    databaseURL: 'https://srimanjunathalocationservices-default-rtdb.firebaseio.com',
    storageBucket: 'srimanjunathalocationservices.firebasestorage.app',
    measurementId: 'G-5ESRNBBLSX',
  );
}
